language: android
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libglew-dev libglu1-mesa-dev libxmu-dev libxi-dev libsdl-dev libxxf86vm-dev libxmu-dev libxcb1-dev libxcb-randr0-dev libxcb-util0-dev
install: true
before_script: bash ./bin/ci-linux.sh
script: bash ./bin/ci-android.sh

